modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      headers:
        Scheme: https
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"
      fail_if_not_ssl: true
      # OAuth 2.0 configuration to use to connect to the targets.
      # oauth2:
      #   client_id: <string>
      #   client_secret: <secret>
      #   # Read the client secret from a file.
      #   # It is mutually exclusive with `client_secret`.
      #   client_secret_file: <filename>
      #   # Scopes for the token request.
      #   scopes:
      #     - <string>
      #   # The URL to fetch the token from.
      #   token_url: <string>
      #   # Optional parameters to append to the token URL.
      #   endpoint_params:
      #     [ <string>: <string> ... ]
