apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-blackbox-exporter.fullname" . }}
  labels:
    {{- include "prometheus-blackbox-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prometheus-blackbox-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus-blackbox-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prometheus-blackbox-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9115
              protocol: TCP
          args:
            - '--config.file=/configmaps/blackbox/blackbox.yaml'
            - --log.level={{ .Values.log.level }}
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: blackbox
              mountPath: /configmaps/blackbox
            - name: okta
              mountPath: /secrets/okta
            {{- if .Values.tls_verify.enabled }}
            - name: ingressgateway-rootca
              mountPath: /secrets/ingressgateway-rootca
            {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: blackbox
          configMap:
            name: blackbox
            defaultMode: 420
        - name: okta
          secret:
            secretName: okta
            defaultMode: 420
        {{- if .Values.tls_verify.enabled }}
        - name: ingressgateway-rootca
          secret:
            secretName: ingressgateway-rootca
            defaultMode: 420
        {{- end }}
